services:
  - type: web
    name: trackt-ticketing
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
